use_frameworks!

platform :ios, '10.0'

target 'MKDeltrtackMQTT_Example' do
  pod 'MKDeltrtackMQTT', :path => '../'

  target 'MKDeltrtackMQTT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
